spring.application.name=demo

server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/inventory_playground}
spring.datasource.username=${DB_USERNAME:inventory}
spring.datasource.password=${DB_PASSWORD:amir123}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true